### PR TITLE
how vim/neovim use dictionary

### PR DESCRIPTION
**Pull request by ayoubelmhamdi**
I mention in readme how `neovim` load dics by `set dictionary`

### CODE REVIEW

**Comment by uga-rosa** [comment]
Thank you.
I'll reimplement it asynchronously to support a larger dictionary first. I feel like using cmp-look would be better for this application, but...

**Comment by uga-rosa** [comment]
With the current implementation, handling 100,000 dictionaries would be very laggy, wouldn't it?

**Comment by ayoubelmhamdi** [comment]
yah i cant use huge dic yet

**Comment by uga-rosa** [comment]
I've made it asynchronous and added this PR content as well.

**Pull request closed without merging**
